// Shared mock data for the Century Advantage UI kit.
// Pulled / adapted from the codebase's seed listings.

window.CA_MOCKS = {
  listings: [
    {
      id: 'p1',
      type: 'Resale',
      project: 'Century Ethos',
      location: 'Hebbal, Bengaluru',
      bhk: 3,
      area: '2,140',
      floor: '14 of 22',
      facing: 'East',
      furnishing: 'Semi Furnished',
      possession: 'Ready to Move',
      priceStr: '₹2.4 Cr',
      price: 24000000,
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=80',
      tagline: 'Penthouse, top of the Hebbal skyline',
    },
    {
      id: 'p2',
      type: 'Rental',
      project: 'Century Renata',
      location: 'Sarjapur Road, Bengaluru',
      bhk: 3,
      area: '1,840',
      floor: '9 of 18',
      facing: 'North-East',
      furnishing: 'Fully Furnished',
      possession: 'Immediate',
      priceStr: '₹85,000/mo',
      price: 85000,
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
      tagline: '3 BHK overlooking the clubhouse pool',
    },
    {
      id: 'p3',
      type: 'Resale',
      project: 'Century Indus',
      location: 'Whitefield, Bengaluru',
      bhk: 4,
      area: '3,210',
      floor: '7 of 12',
      facing: 'West',
      furnishing: 'Unfurnished',
      possession: 'Ready to Move',
      priceStr: '₹3.8 Cr',
      price: 38000000,
      image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=80',
      tagline: 'Garden duplex with private terrace',
    },
    {
      id: 'p4',
      type: 'Rental',
      project: 'Century Breeze',
      location: 'Jakkur, Bengaluru',
      bhk: 2,
      area: '1,260',
      floor: '4 of 10',
      facing: 'South',
      furnishing: 'Semi Furnished',
      possession: 'Immediate',
      priceStr: '₹42,000/mo',
      price: 42000,
      image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80',
      tagline: '2 BHK near the Yelahanka greens',
    },
    {
      id: 'p5',
      type: 'Resale',
      project: 'Century Linea',
      location: 'Thanisandra, Bengaluru',
      bhk: 3,
      area: '1,920',
      floor: '11 of 15',
      facing: 'East',
      furnishing: 'Fully Furnished',
      possession: 'Mar 2027',
      priceStr: '₹2.1 Cr',
      price: 21000000,
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80',
      tagline: 'Corner unit, north-light all day',
    },
    {
      id: 'p6',
      type: 'Rental',
      project: 'Century Eras',
      location: 'Hebbal, Bengaluru',
      bhk: 4,
      area: '2,580',
      floor: '17 of 20',
      facing: 'East',
      furnishing: 'Fully Furnished',
      possession: 'Immediate',
      priceStr: '₹1,25,000/mo',
      price: 125000,
      image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80',
      tagline: 'Sky duplex with terrace garden',
    },
  ],

  amenities: [
    '24×7 Concierge', 'Clubhouse', 'Swimming Pool', 'Gym & Spa',
    'Co-working Lounge', 'Reserved Parking', 'EV Charging', 'Power Backup',
    'Children\u2019s Play Area',
  ],

  nearby: ['Hebbal Lake (1.2 km)', 'Manyata Tech Park (3.4 km)', 'Esteem Mall (2.1 km)', 'Embassy Hospital (4.8 km)'],
};
